### ISSUE TITLE
not pass tests

### ISSUE THREAD

**Issue by pnatsi** [Rinoahu/SwiftOrtho#3]
Hi,

I download SwiftOrtho and ran the tests, but they failed to complete. Here is the error message:

('chk size', 50000)
Traceback (most recent call last):
  File "../bin/find_cluster.py", line 22, in <module>
    import networkx as nx
ImportError: No module named networkx
Traceback (most recent call last):
  File "../bin/find_cluster.py", line 22, in <module>
    import networkx as nx
ImportError: No module named networkx
not pass test 1
nohup: ignoring input and redirecting stderr to stdout
('all to all homologous searching time:', 61.62682485580444)
('orthomcl algorithm time:', 1.9388201236724854)
nohup: ignoring input and redirecting stderr to stdout
Traceback (most recent call last):
  File "../scripts/run_all.py", line 177, in <module>
    out = '\t'.join(k)
TypeError: sequence item 0: expected string, NoneType found
not pass test 2

**Comment by Rinoahu** [comment]
The error shows that the **_networkx_** package of python is not installed. If you use conda, you install it by running the command: _**conda install -c anaconda networkx**_.. If you are familiar with pip, you can also install it by running the command: **_pip install networkx_**. Or you can download the source code at https://networkx.github.io/ and install it manually.

**Comment by Rinoahu** [comment]
> The error shows that the **_networkx_** package of python is not installed. If you use conda, you install it by running the command: _**conda install -c anaconda networkx**_.. If you are familiar with pip, you can also install it by running the command: **_pip install networkx_**. Or you can download the source code at https://networkx.github.io/ and install it manually.

**Comment by Rinoahu** [comment]
> Hi,
> 
> I download SwiftOrtho and ran the tests, but they failed to complete. Here is the error message:
> 
> ('chk size', 50000)
> Traceback (most recent call last):
> File "../bin/find_cluster.py", line 22, in 
> import networkx as nx
> ImportError: No module named networkx
> Traceback (most recent call last):
> File "../bin/find_cluster.py", line 22, in 
> import networkx as nx
> ImportError: No module named networkx
> not pass test 1
> nohup: ignoring input and redirecting stderr to stdout
> ('all to all homologous searching time:', 61.62682485580444)
> ('orthomcl algorithm time:', 1.9388201236724854)
> nohup: ignoring input and redirecting stderr to stdout
> Traceback (most recent call last):
> File "../scripts/run_all.py", line 177, in 
> out = '\t'.join(k)
> TypeError: sequence item 0: expected string, NoneType found
> not pass test 2

The error shows that the **_networkx_** package of python is not installed. If you use conda, you install it by running the command: _**conda install -c anaconda networkx**_.. If you are familiar with pip, you can also install it by running the command: **_pip install networkx_**. Or you can download the source code at https://networkx.github.io/ and install it manually.

**Comment by weifei888** [comment]
i didn't pass the test 2, and i found i got all the result except the "ref.fas.pan" which is 0 byte, where or which file should i check?

**Comment by Rinoahu** [comment]
Hi, could you please upload the log file?
